# Railway Configuration for Todo Backend

[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# These will be set in Railway dashboard or via CLI
# DATABASE_URL is automatically set when you add PostgreSQL plugin
# PORT is automatically set by Railway
